<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-B0D0J2Q" failures="1" tests="1" name="Positive Login Tests" time="6.89" errors="0" timestamp="2025-03-19T23:45:11 ICT">
  <testcase classname="com.practicetestautomation.tests.login.PositiveLoginTests" name="testLoginFunctionality" time="6.782">
    <failure type="java.lang.AssertionError" message="expected [https://practicetestautomation.com/logged-in-successfully/] but found [https://practicetestautomation.com/practice-test-login/]">
      <![CDATA[java.lang.AssertionError: expected [https://practicetestautomation.com/logged-in-successfully/] but found [https://practicetestautomation.com/practice-test-login/]
at com.practicetestautomation.tests.login.PositiveLoginTests.testLoginFunctionality(PositiveLoginTests.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- testLoginFunctionality -->
</testsuite> <!-- Positive Login Tests -->
